servers:
  - user: "vagrant"
    password: "vagrant"
    host: "192.168.56.201"
    port: "22"
    commands:
      - "uptime"
  - user: "vagrant"
    password: "vagrant"
    host: "192.168.56.202"
    port: "22"
    commands:
      - "df -k"
  - user: "vagrant"
    password: "vagrant"
    host: "192.168.56.203"
    port: "22"
    commands:
      - "free -m"
      - "sudo find /var/spool/postfix/ -type f | wc -l"
